service:
  env: staging

  ingress:
    hosts:
      - hosts: assessmentcloud.com
        path: /
        pathType: Prefix
    tls:
      - hosts:
          - assessmentcloud.com
        secretName: helloworld-tls